### ISSUE TITLE
Does veryfi-lens-react-native work with expo? 

### ISSUE THREAD

**Issue by m1thrandir225** [veryfi/veryfi-lens-react-native-demo#22]
Will the react native package work with an expo project?

**Comment by alejouribesanchez** [comment]
@jamesmgt has an example project of that. Could you share it?

**Comment by m1thrandir225** [comment]
Yeah that would be nice

**Comment by GibbyBox** [comment]
Can you release the config plugin used at least?

I'm using this with our expo project, but we only have an ios app so I haven't looked into the work required to get it working with android.
For ios, it's a simple matter of adding entries to the `ios.infoPlist` field in the app config. I'd imagine it would be a bit more involved for android.
In either case, a usable config plugin would be great for anyone on expo.
